
package Formularios;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;



public class MDIPrincipal extends javax.swing.JFrame {
    
    frmProvincias fProvincias = null ;
    frmTiposdePaquetes fTipopaquete = null ;
    frmClientes fClientes = null ;
    frmEncomienda fEncomienda = null ;
    frmFactura fFactura = null ;

    public MDIPrincipal() {
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Cachiflin Express");
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        String ImagenFondo = "" ;
        int Segundo = (int) (System.currentTimeMillis() % 10 );
        if ( Segundo <= 3 )
        { ImagenFondo = "/Imagenes/Cachiflin.jpg" ; }
        else if ( Segundo <= 6 )
        { ImagenFondo = "/Imagenes/Cachiflin2.jpg" ; }
        else 
        { ImagenFondo = "/Imagenes/Cachiflin3.jpg" ; }

        ImageIcon icon = new ImageIcon(getClass().getResource(ImagenFondo));
        Image img = icon.getImage();
        Escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g)
            {
                g.drawImage(img,0,0,getWidth(),getHeight(),this);
            }
        }
        ;
        menuBar = new javax.swing.JMenuBar();
        mnProcesos = new javax.swing.JMenu();
        mnEncomienda = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        mnFactura = new javax.swing.JMenuItem();
        mnCatalogo = new javax.swing.JMenu();
        mnProvincias = new javax.swing.JMenuItem();
        mnPaquete = new javax.swing.JMenuItem();
        mnClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnProcesos.setMnemonic('f');
        mnProcesos.setText("Procesos");

        mnEncomienda.setMnemonic('o');
        mnEncomienda.setText("Tramitar Encomienda");
        mnEncomienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEncomiendaActionPerformed(evt);
            }
        });
        mnProcesos.add(mnEncomienda);

        menuBar.add(mnProcesos);

        mnConsultas.setMnemonic('e');
        mnConsultas.setText("Consultas");

        mnFactura.setMnemonic('t');
        mnFactura.setText("Facturas");
        mnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFacturaActionPerformed(evt);
            }
        });
        mnConsultas.add(mnFactura);

        menuBar.add(mnConsultas);

        mnCatalogo.setMnemonic('h');
        mnCatalogo.setText("Cátalogos");

        mnProvincias.setMnemonic('c');
        mnProvincias.setText("Provincias");
        mnProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProvinciasActionPerformed(evt);
            }
        });
        mnCatalogo.add(mnProvincias);

        mnPaquete.setMnemonic('a');
        mnPaquete.setText("Tipos de Paquete");
        mnPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPaqueteActionPerformed(evt);
            }
        });
        mnCatalogo.add(mnPaquete);

        mnClientes.setText("Clientes");
        mnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClientesActionPerformed(evt);
            }
        });
        mnCatalogo.add(mnClientes);

        menuBar.add(mnCatalogo);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProvinciasActionPerformed
        if ( fProvincias == null || fProvincias.isClosed())
        {
        fProvincias = new frmProvincias() ;
        Escritorio.add(fProvincias) ;
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = fProvincias.getSize();
        fProvincias.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);

        }
        fProvincias.toFront();
        fProvincias.setVisible(true);
       
    }//GEN-LAST:event_mnProvinciasActionPerformed

    private void mnPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPaqueteActionPerformed
         if ( fTipopaquete==null || fTipopaquete.isClosed() )
        {
        fTipopaquete = new frmTiposdePaquetes();
        Escritorio.add(fTipopaquete);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = fTipopaquete.getSize();
        fTipopaquete.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        }
        
        fTipopaquete.toFront();
        fTipopaquete.setVisible(true);
    }//GEN-LAST:event_mnPaqueteActionPerformed

    private void mnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClientesActionPerformed
         if ( fClientes==null || fClientes.isClosed() )
        {
        fClientes = new frmClientes();
        Escritorio.add(fClientes);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = fClientes.getSize();
        fClientes.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        }
        
        fClientes.toFront();
        fClientes.setVisible(true);
    }//GEN-LAST:event_mnClientesActionPerformed

    private void mnEncomiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEncomiendaActionPerformed
         if ( fEncomienda==null || fEncomienda.isClosed() )
        {
        fEncomienda = new frmEncomienda();
        Escritorio.add(fEncomienda);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = fEncomienda.getSize();
        fEncomienda.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        }
        
        fEncomienda.toFront();
        fEncomienda.setVisible(true);
    }//GEN-LAST:event_mnEncomiendaActionPerformed

    private void mnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFacturaActionPerformed
         if ( fFactura == null || fFactura.isClosed() )
        {
        fFactura = new frmFactura();
        Escritorio.add(fFactura);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = fFactura.getSize();
        fFactura.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        }
        
        fFactura.toFront();
        fFactura.setVisible(true);
    }//GEN-LAST:event_mnFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnCatalogo;
    private javax.swing.JMenuItem mnClientes;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenuItem mnEncomienda;
    private javax.swing.JMenuItem mnFactura;
    private javax.swing.JMenuItem mnPaquete;
    private javax.swing.JMenu mnProcesos;
    private javax.swing.JMenuItem mnProvincias;
    // End of variables declaration//GEN-END:variables

}
